### ISSUE TITLE
Motor Current Measurement

### ISSUE THREAD

**Issue by krucka** [CytronTechnologies/CytronMotorDriver#14]
Is it possible to get the value of the current for loading purposes without having to install a separate current sensor in series with the motor leads?  E.g. linear actuator installed on a swing gate to detect when it's come in contact with an obstacle.  It seems like given the motor drive can limit the current when overloaded, it should be possible to read the current via code but the only method listed is setSpeed, and I'm requesting, if possible, to add getCurrent.

**Comment by waiweng83** [comment]
Unfortunately that's not possible. None of the Cytron's motor driver support current readback for now.
