### ISSUE TITLE
Which pins can I use?

### ISSUE THREAD

**Issue by bylli79** [CytronTechnologies/CytronMotorDriver#4]
Hello,
I use Arduino UNo.
Arduino UNO uses pins 3,9,10,11 at 490 Hz.
Use pins 5 and 6: 980 Hz.
Can I use pins 5 and 6 with the MDD3A board?
Is the frequency of 980 Hz too high?

Thanks

**Comment by waiweng83** [comment]
The MDD3A supports input PWM frequency up to 20kHz.
Thus, it is perfectly fine to use it with pin 5 & 6 of the Arduino UNO.
