### ISSUE TITLE
Cytron Shield-MDD10

### ISSUE THREAD

**Issue by Mr-Caldwell** [CytronTechnologies/CytronMotorDriver#8]
Hello,

I am having trouble using the sample code for dual motors on an Arduino Uno with a Shield-MDD10. 

It will function normally if I use "setSpeed(255);" or "setSpeed(-255);", but if I set the speed to anything less than 255, ("setSpeed(128)" for example) only one motor will actually run, and the other motor stops moving entirely.

Any ideas on what I could be doing wrong?

**Comment by waiweng83** [comment]
Are the PWM & DIR pins defined correctly according to the jumper settings on the SHIELD-MDD10?

**Comment by Mr-Caldwell** [comment]
Yes, the jumpers are connected as follows:
PWM1 : pin 9
DIR1 : pin 8
PWM2 : pin 11
DIR2 : pin 13

And that is also how I have them initialized in my code.

**Comment by waiweng83** [comment]
Please contact support@cytron.io in that case.
Do share with us the code you used to test it too.

Thanks.
